# Generated by Django 4.1 on 2024-01-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="diseasestreemap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Disease_ID", models.IntegerField(verbose_name="Diseases_ID")),
                (
                    "Disease_Name",
                    models.CharField(max_length=250, verbose_name="Disease_Name"),
                ),
                (
                    "Disease_Type",
                    models.CharField(max_length=250, verbose_name="Disease_Type"),
                ),
                ("DALYRate", models.IntegerField(verbose_name="DALYRate")),
            ],
        ),
    ]
