# Generated by Django 4.1 on 2024-01-02 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Healthapp", "0003_servicenew_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subservicenew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("directinpts", models.CharField(max_length=100)),
                ("resources", models.CharField(max_length=100)),
                ("value", models.IntegerField()),
                (
                    "subservice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Healthapp.servicenew",
                    ),
                ),
            ],
        ),
    ]
