# Generated by Django 4.1 on 2024-01-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Healthapp", "0004_subservicenew"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subservicenew",
            name="subservice",
            field=models.CharField(max_length=100),
        ),
    ]
