# Generated by Django 4.1 on 2024-01-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Healthapp", "0005_alter_subservicenew_subservice"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subservice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
