from django.urls import path
from . import views
urlpatterns =[
    path('', views.index, name='index'),
    path('treemap_view/',views.treemap_view,name='treemap_view'),
    path('disease/<str:disease_name>/',views.disease_treemap, name='disease_treemap'),
    path('subservice/<str:subservice_name>/',views.subservice_view, name='subservice_view'),
    path('barchart/', views.barchart, name='barchart'),
    path('speedometer/',views.speedometer_chart,name='speedometer_chart'),
    path('picture/',views.my_view, name='my_view'),
    path('his/',views.his, name='his'),
    path('quality/', views.quality, name='quality'),
    path('justice/', views.justice, name='justice'),
    path('efficiency/',views.efficiency, name='efficiency'),
    path('sustainability/',views.sustainability, name='sustainability'),
    path('frontpage/', views.frontpage, name='frontpage'),
    path('register/',views.register, name='register'),
    path('barchartnew/',views.barchartnew, name='barchartnew'),
    path('guagechart/',views.guagechart, name='guagechart'),
    path('progresschart/',views.progresschart, name='progresschart'),
    path('login/',views.login, name='login'),
    path('logout/',views.logout, name='logout'),
    path('hf/', views.hf, name='hf'),
    path('target/', views.target, name='target'),
    path('button/', views.button, name='button'),
    path('line/', views.line, name='line'),
    path('bubble_chart/', views.bubble_chart, name='bubble_chart'),
    path('Access/',views.access, name='access'),
    path('another-page/', views.another_page_view, name='another_page'),
    path('quality2/', views.quality2, name='quality2'),
    path('quality3/', views.quality3, name='quality3'),
]
